# Fastlane for Android (template)
default_platform(:android)

platform :android do
  desc "Build and upload to Google Play (internal testing)"
  lane :internal do
    gradle(task: "clean")
    gradle(task: "assemble", build_type: "Release")
    upload_to_play_store(
      track: "internal",
      json_key_data: ENV["GOOGLE_PLAY_JSON"],
      package_name: "com.assafarma.reports"
    )
  end
end