name: Android CI

on:
  push:
<<<<<<< HEAD
    branches: [ main ]
    tags:
      - "v*.*.*"

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Upload artifact (APK)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/*.apk
=======
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # הגדרת סביבת Java. הסרנו את ה-cache כדי למנוע שגיאה.
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    # מתן הרשאות הפעלה לקובץ gradlew במיקום הנכון.
    - name: Grant execute permission for gradlew
      run: chmod +x android_fastlane/gradlew

    # ניווט לתיקייה הנכונה והפעלת פקודת הבנייה של Gradle.
    - name: Build with Gradle
      run: |
        cd android_fastlane
        ./gradlew build

    # העלאת ה-Artifact. יש לוודא שהנתיב נכון.
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-release-apk
        path: android_fastlane/app/build/outputs/apk/debug/app-debug.apk
>>>>>>> 9509172efa08dcd0b6bb13a3cbdaa026b0c76ba2
